#!/usr/bin/env bash
# Copyright 2023 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Runs project.

# [Setup]
set -u
set -e
# Capture caller directory and script directory.
readonly calling_dir="$(pwd)"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./_gscript

# [Main]

if [ $# -lt 1 ]; then
    echoerr "Need the name of the project."
fi
name=$1

shift
readonly args=$*

# Build.
./build MinSizeRel

# Run.
echo "${c_bold}${cf_black}Running: ${cf_white}${name}${c_reset}"
"./code/bin/${name}" $args

# [Teardown]
cd "${calling_dir}"
